### ISSUE TITLE
craftbench speed up doesn't

### ISSUE THREAD

**Issue by gnarlyCrone** [SifVerT/DifficultyTuner#2]
If you change the workbench speed setting the tick sound and counter go faster but the timing of output never changed. EG if you are making an item with a time of 180 and you set the speed to 200%. It will go twice as fast but require 360 ticks to complete. No change to the craftbench settings result in an actual speed increase.

**Comment by SifVerT** [comment]
The issue has been fixed internally. It worked but the speed was inverted meaning a lower value meant a faster crafting speed. It was a typo in the maths involved.
