### ISSUE TITLE
crashes in u6

### ISSUE THREAD

**Issue by gnarlyCrone** [SifVerT/DifficultyTuner#3]
(I am not too knowledgable and hope I am providing the correct info.) 
Worked fine in U5. Every time I try to run the mod in U6 it crashes. The info says: SML\Source\SML\Public\Reflection/BlueprintReflectionLibrary.h] [Line: 142] GetClassDefaultObject: received NULL class
This happens with this mod whether run with others or alone. 

I hope this info helps you to fix the problem. Thank you.

**Comment by SifVerT** [comment]
Please select the version before latest version if on U6. I'm working on a new version for U6 specifically.

**Comment by gnarlyCrone** [comment]
Thank you
